#! /bin/sh
#
# Example panel for LemonBoy's bar

source $(dirname $0)/config.sh

. /home/ogremagi/.config/bspwm/dark_bar/panel_colors

num_mon=$(bspc query -M | wc -l)

while read -r line ; do
	case $line in
		S*)
			# clock output
      #tmp=`echo -e "$(sensors coretemp-isa-0000 | awk '/Physical/ { print $4 }')"`
      #mem=`echo -e "$(free -m | grep "\-/\+" | awk '{print $3}')Mb"`
      art=`[[ $(mpc -f %artist% | awk '{print $1}' ) == "volume:100%" ]]  || echo -e "%{F$BLUE}$MUSIC %{F$THECOLOR}$(mpc -f %artist% | awk 'NR==1') -"`
      tit=`[[ $(mpc -f %title% | awk '{print $1}' ) == "volume:100%" ]]  || echo -e "$(mpc -f %title% | awk 'NR==1')"`
      vol=`amixer sget Master | sed -n "0,/.*\[\([0-9]\+\)%\].*/s//\1/p"`
      #wifissid=`if [[ $(iwgetid -r) == "" ]]; then echo -e "Wifi Down"; else iwgetid -r; fi`
      #wifistr=`panel_wifi`
      #batt=`acpi -b | awk '{ split($5,a,":"); print substr($3,0,2), $4, "["a[1]":"a[2]"]" }' | tr -d ',' | sed -e 's/\[//g;s/\]//g'`
      #batt=`bat.sh`
      package=`pacman -Qq | wc -l`
      clk=`date "+%I:%M %p"`
			clk2=`date "+%b %d"`
      sys_infos="%{F$COLOR_STATUS_FG}%{B$COLOR_STATUS_BG} %{F$YELLOW}${PACIC}%{F$FOREG} ${package} %{F$THECOLOR}${SOUNDIC} %{F$FOREG}${vol}%% %{F$GREEN}${CALIC} %{F$FOREG}${clk2} %{F$THECOLOR}${CLKIC} %{F$FOREG}${clk}"
      ;;
		T*)
			# xtitle output
			title="%{F$COLOR_TITLE_FG}%{B$COLOR_TITLE_BG} ${line#?} %{B-}%{F-}"
			;;
		W*)
			# bspwm internal state
			wm_infos=""
			IFS=':'
			set -- ${line#?}
			while [ $# -gt 0 ] ; do
				item=$1
				name=${item#?}
				case $item in
					M*)
						# active monitor
						if [ $num_mon -gt 1 ] ; then
							wm_infos="$wm_infos %{F$COLOR_ACTIVE_MONITOR_FG}%{B$COLOR_ACTIVE_MONITOR_BG}${name}%{B-}%{F-}  "
						fi
						;;
					m*)
						# inactive monitor
						if [ $num_mon -gt 1 ] ; then
							wm_infos="$wm_infos %{F$COLOR_INACTIVE_MONITOR_FG}%{B$COLOR_INACTIVE_MONITOR_BG} ${name}%{B-}%{F-}"
						fi
						;;
					O*)
						# focused occupied desktop
						wm_infos="${wm_infos}%{F$COLOR_FOCUSED_OCCUPIED_FG}%{B$COLOR_FOCUSED_OCCUPIED_BG}%{U$COLOR_FOREGROUND}%{+u} ${WSIC}%{-u}%{B-}%{F-}"
						;;
					F*)
						# focused free desktop
						wm_infos="${wm_infos}%{F$COLOR_FOCUSED_FREE_FG}%{B$COLOR_FOCUSED_FREE_BG}%{U$COLOR_FOREGROUND}%{+u} ${WSIC}%{-u}%{B-}%{F-}"
						;;
					U*)
						# focused urgent desktop
						wm_infos="${wm_infos}%{F$COLOR_FOCUSED_URGENT_FG}%{B$COLOR_FOCUSED_URGENT_BG}%{U$COLOR_FOREGROUND}%{+u} ${WSIC}%{-u}%{B-}%{F-}"
						;;
					o*)
						# occupied desktop
						wm_infos="${wm_infos}%{F$COLOR_OCCUPIED_FG}%{B$COLOR_OCCUPIED_BG} ${WSIC}%{B-}%{F-}"
						;;
					f*)
						# free desktop
						wm_infos="${wm_infos}%{F$COLOR_FREE_FG}%{B$COLOR_FREE_BG} ${WSIC}%{B-}%{F-}"
						;;
					u*)
						# urgent desktop
						wm_infos="${wm_infos}%{F$COLOR_URGENT_FG}%{B$COLOR_URGENT_BG} ${WSIC} %{B-}%{F-}"
						;;
					L*)
						# layout
						#wm_infos="$wm_infos  %{F$COLOR_LAYOUT_FG}%{B$COLOR_LAYOUT_BG} ${name} %{B-}%{F-}"
						;;
				esac
				shift
			done
			;;
	esac
	printf "%s\n" "%{l} %{F$THECOLOR}${art}%{F$FOREG} ${tit} %{c} ${wm_infos} ${title} %{r} $sys_infos "
done
